services:
  - type: web
    name: autofix-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: FLASK_ENV
        value: production
